version: '3.8'

services:
  db:
    image: postgres:15
    container_name: finance_pg_db
    restart: always
    environment:
      POSTGRES_USER: ishitajain
      POSTGRES_PASSWORD: postgres123!
      POSTGRES_DB: finance_data
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pg_data:
